# Generated by Django 4.2.3 on 2023-07-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilidades', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='movilidad',
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
